#!/usr/bin/env bash
# This script installs and configures Nginx to listen on port 80.

# Update package index and install Nginx
apt-get update
apt-get install -y nginx

# We Configure Nginx to listen on all active IPv4 addresses
sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
systemctl restart nginx

# Enable Nginx to start on boot
systemctl enable nginx

