#!/usr/bin/env bash
# this script changes the ip addres of some distinations in the hostname file.
cp /etc/hosts ~/hosts.new
sed -i '/^127\.0\.0\.1/d;$a\127.0.0.2	localhost'  ~/hosts.new
sed -i '/^157\.240\.11\.35/d;$a\8.8.8.8	facebook.com'  ~/hosts.new
cp -f ~/hosts.new /etc/hosts
